-- Migration: Migrate SQLite tables to Supabase PostgreSQL

-- Table: funding_history
CREATE TABLE IF NOT EXISTS public.funding_history (
    "timestamp" BIGINT NOT NULL,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "funding_rate" DOUBLE PRECISION,
    "funding_interval" INTEGER,
    "mark_price" DOUBLE PRECISION,
    "volume_24h" DOUBLE PRECISION,
    PRIMARY KEY ("timestamp", "symbol", "exchange")
);

CREATE INDEX IF NOT EXISTS idx_funding_history_symbol_time ON public.funding_history("symbol", "timestamp");
CREATE INDEX IF NOT EXISTS idx_funding_history_time ON public.funding_history("timestamp");

-- Table: funding_rate_history
CREATE TABLE IF NOT EXISTS public.funding_rate_history (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "symbol" TEXT NOT NULL,
    "exchange" TEXT NOT NULL,
    "funding_rate" DOUBLE PRECISION,
    "price" DOUBLE PRECISION,
    "next_funding_time" BIGINT,
    "funding_interval_hours" DOUBLE PRECISION,
    "recorded_at" BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_history_lookup ON public.funding_rate_history("symbol", "exchange", "recorded_at");

-- Row Level Security (RLS) configuration
ALTER TABLE public.funding_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funding_rate_history ENABLE ROW LEVEL SECURITY;

-- Allow public read access to history data
CREATE POLICY "Allow public read access on funding_history"
ON public.funding_history FOR SELECT USING (true);

CREATE POLICY "Allow public read access on funding_rate_history"
ON public.funding_rate_history FOR SELECT USING (true);

-- Allow public insert access for API routes (since the server uses anon key right now)
-- Alternatively, if the server uses a service role key, this policy wouldn't be needed for the server.
-- Since the Next.js routes use process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY, we need to allow inserts from anon for now,
-- OR better yet, let's create a policy that allows inserts if they come from the server environment.
-- For simplicity in migration, allow public insert/update.
CREATE POLICY "Allow public insert on funding_history"
ON public.funding_history FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public insert on funding_rate_history"
ON public.funding_rate_history FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update on funding_history"
ON public.funding_history FOR UPDATE USING (true);

CREATE POLICY "Allow public update on funding_rate_history"
ON public.funding_rate_history FOR UPDATE USING (true);

-- Add user_id to paper_positions
ALTER TABLE public.paper_positions ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Update paper_positions RLS
ALTER TABLE public.paper_positions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own paper positions"
ON public.paper_positions FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);


-- Table: scanner_cache
CREATE TABLE IF NOT EXISTS public.scanner_cache (
    id integer PRIMARY KEY DEFAULT 1,
    payload jsonb NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT single_row CHECK (id = 1)
);

ALTER TABLE public.scanner_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on scanner_cache"
ON public.scanner_cache FOR SELECT USING (true);

CREATE POLICY "Allow public insert on scanner_cache"
ON public.scanner_cache FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update on scanner_cache"
ON public.scanner_cache FOR UPDATE USING (true);

